# Site settings
title: Tour Guide
email: 
description: "Tour guides help you discover the wonders of the world. Book tour guides and private tours in amasing destinations worldwide. "
baseurl: ""
url: "http://tour-guide.com/"

# Build settings
markdown: kramdown
permalink: pretty
